### PR TITLE
Removed signal handling.

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Comment by jmachowinski** [comment]
If you remove this, you will loose the nice stacktraces on crash.
Also you might end up with zombies.
Is there a particular reason for removing the code ?

**Comment by skasperski** [comment]
Because it conflicts with orogen's signal handling. How will one end up with zombies? Note that I removed the handling of this process' own signals, not the handling for launched child processes.

**Comment by jmachowinski** [comment]
Now you got me confused. The spawner was intended, to just spawn child processes, that run the orogen containers. 
Inside of the process, that runs the spawner, there should be no orogen signal handlers present. 

Are you using the spawner inside of orogen generated code ?

Also, these handlers, 'preserve' the original handlers. Meaning, they get called, and afterwards they reinstall whatever signal hander was there before, and then call these. 

The zombies will be created, if the child processes that were spawned are not correctly handled. 
e.g. 
Spawner::getInstace().killAll(); 
does this.

**Comment by skasperski** [comment]
> Are you using the spawner inside of orogen generated code ?

Yes, that's what has been done. And we end up with the task not being finished at all.

@maltewi : This might be a hint towards the issue with the Process-Server.

**Comment by maltewi** [comment]
@skasperski I think the issue is solved. If you agree, could you please close this PR?

**Comment by skasperski** [comment]
It seems not to be solved for me. And even disregarding the special case of running the spawner in an orogen component, I think signal handling should not be done in a library. The method killAll() is there, and every user of orocos_cpp is free to catch signals and call killAll() from within the handler if required. I believe it should not be done by the library itself.

**Comment by skasperski** [comment]
This PR has become obsolete now, because the target branch is not used anymore. I create a new one to merge this change into master.

**Pull request closed without merging**
