### PR TITLE
TypeWrapper class to easily introspect and use fields of typelib types

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by maltewi** [comment]
Have you been aware of  `lib_config::ConfigValue` (https://github.com/rock-cpp/lib_config/blob/master/src/Configuration.hpp)? If yes can you quickly state how your solution relates to this?

Have i.e. a look here for an example https://git.hb.dfki.de/dfki-control/modeling/cnd-execution/-/blob/read_write_ports/src/ConfigValuePortReader.cpp#L98

**Comment by planthaber** [comment]
I was not aware of the lib_config::ConfigValue, but of the [ConfigurationHelper](https://github.com/rock-cpp/orocos_cpp/blob/master/src/ConfigurationHelper.cpp) in this repo.

As I saw it, they are both limited to yaml outputs (data already converted to string).

I needed a version that allows me to directly read the values (e.g. double) within cpp code or just convert a single value out of a compound type to string.

Ultimately this will be used to create a direct rock interface to [plotjuggler](https://plotjuggler.io/) [DFKI internal link](https://git.hb.dfki.de/sw-backbone/testing/gui-plotjuggler_rock) (gui/plotjuggler_rock)

**Comment by planthaber** [comment]
With respect to the ConfigurationHelper, we could think of letting that one use this class in order to reduce duplicate code, but the use case is different: [Configuration.hpp](https://github.com/rock-cpp/lib_config/blob/master/src/Configuration.hpp) is used mainly to read yaml configurations into typelib types, where this class is used to have introspection access to a typelib type within cpp code.

It can be used to read any rock port without type or typekit dependencies [main5.cpp](https://github.com/rock-cpp/orocos_cpp/blob/ea72990c2a0e0f9fbf9372751dc9ba3113901fc0/src/main5.cpp) is an example of reading and printing all ports that currently write a "/base/samples/joints" type.

**Comment by planthaber** [comment]
@maltewi are you now ok with merging?

**Comment by maltewi** [comment]
To better illustrate how similar both approaches are I've added an example that does the same as TypeWrapper but with lib_configs ConfigValue (https://github.com/rock-cpp/orocos_cpp/blob/TypeWrapper/src/main6.cpp).

See below the list of differences between both approaches and please extend if you find something. Please also have a look and complete the options for harmonization so that we can come up with a single solution that fulfills all needs.

### Collection of similarities and differences

#### ConfigValue misses:
* comfortable field getter (extract_field-function)
* conversion to primitive types

#### TypeWrapper misses:
* comparision operators
* yaml emitters

### Options for harmonization
#### O1: Migration to TypeWrapper
* [ ] Close open gaps
* [ ] Migrate lib:config::Configuiration to TypeWrapper (values variable)
* [ ] Migrate lib_config::YAMLConfigParser to TypeWrapper 

#### O2: Migration to lib_config::ConfigValue
* [ ] Close open gaps

My current opinion on this: I personally like the TypeWrapper and also the fact that it's inside the orocos_cpp lib instead of lib_config. Switching to TypeWrapper would be totally fine for me.

The effort of migrating to TypeWrapper appears to be higher than closing the gaps in the ConfigValue-approach. If you can put some additional effort into this, a full migration to TypeWrapper would be more than welcome. Which of the open points could you solve?

**Comment by planthaber** [comment]
But what is exactly the difference/link between the lib_config::Configuration and orocos_cpp::ConfigurationHelper?

Because I though "Migration to TypeWrapper" would only include making the orocos_cpp::ConfigurationHelper to use the TypeWrapper, because this is actually where the code is doubled.

**Comment by planthaber** [comment]
Also, orocos_cpp::ConfigurationHelper already has yaml emitters, which is not used at all by lib_config.

**Pull request merged**
